services:
  - type: web
    name: clausecraft-py
    env: python
    plan: free
    autoDeploy: true
    pythonVersion: 3.10.13
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false

